#port mqtt
listener 8883

# Izinkan ESP32 masuk tanpa username/password
allow_anonymous true

# Lokasi sertifikat SSL/TLS di dalam kontainer Mosquitto
certfile /mosquitto/config/certs/hvas.crt
keyfile /mosquitto/config/certs/hvas.key

# Menetapkan standar keamanan TLS
tls_version tlsv1.2