events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 443 ssl;
        server_name 34.232.218.0; # Ganti dengan domain jika ada nanti

        # Jalur sertifikat di dalam kontainer Nginx
        ssl_certificate     /etc/nginx/certs/hvas.crt;
        ssl_certificate_key /etc/nginx/certs/hvas.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html; # Penting untuk router Vue.js
        }
    }
}