foreground: true;
inetd: false;
numeric: true;

listen: (
    { host: "0.0.0.0"; port: "8000"; }
);

protocols: (
    # jalur mqtt ALPN: mqtt
    { name: "tls"; alpn_protocols: [ "mqtt" ]; host: "mosquitto"; port: "8883"; },
    
    # jalur apache ALPN: h2, http/1.1
    { name: "tls"; alpn_protocols: [ "h2", "http/1.1" ]; host: "apache-vue"; port: "8443"; },
    
    # jalur tanpa mengirimkan ALPN lemparkan ke apache
    { name: "tls"; host: "apache-vue"; port: "8443"; }
);